# Generated by Django 4.0.4 on 2022-07-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_todo_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
