# Generated by Django 4.0.6 on 2022-08-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_todo_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('date', models.IntegerField()),
                ('isSet', models.BooleanField(default=False)),
            ],
        ),
    ]
