# Generated by Django 4.0.6 on 2022-08-01 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_currdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.currdate'),
        ),
    ]
