# Generated by Django 4.0.6 on 2022-08-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_todo_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currdate',
            name='isSet',
        ),
        migrations.AddField(
            model_name='currdate',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
    ]
